/** Interface strings.
 *
 * These are *chrome* — labels, headings and prompts, authored here in each
 * language. Every number, product term and decision sentence comes from the API
 * in the customer's language, because those are generated from the Decision
 * Object and must not be re-authored here. A second copy of "why we said no" is
 * a second answer to the question.
 *
 * Two honesty constraints follow from that split, and both matter more than the
 * size of this table:
 *
 *  - The chrome is translated. Every key below exists in every language, and
 *    `t()` reports a missing one rather than quietly serving English, so a gap
 *    shows up as a gap instead of as a half-translated screen.
 *  - The *generated* text is authored too, in the reason-code templates and the
 *    Key Fact Statement tables behind it, in the same five languages. What the
 *    prototype still does not have is a live translation service for free-form
 *    text, and `LANGUAGE_COVERAGE_NOTE` says exactly that rather than implying
 *    a coverage it lacks. Report §11.3: language coverage is an integration
 *    claim, not a modelling claim.
 *
 * These strings are authored copy and should be read by a native speaker before
 * any public demonstration.
 */

export type Lang = "hi" | "en" | "mr" | "ta" | "bn";

export const LANGUAGES: { code: Lang; label: string; native: string }[] = [
  { code: "hi", label: "Hindi", native: "हिन्दी" },
  { code: "en", label: "English", native: "English" },
  { code: "mr", label: "Marathi", native: "मराठी" },
  { code: "ta", label: "Tamil", native: "தமிழ்" },
  { code: "bn", label: "Bengali", native: "বাংলা" },
];

type Dict = Record<string, string>;

const STRINGS: Record<Lang, Dict> = {
  en: {
    // navigation and shell
    nav_home: "Overview",
    nav_twin: "Affordability",
    nav_assistant: "Voice guide",
    nav_kfs: "Key facts",
    nav_privacy: "Data & privacy",
    brand_tagline: "banking that stays human",
    utility_left: "ARTHA · Suitability-first lending",
    utility_right: "Every figure in this experience is illustrative",
    hero_eyebrow: "Your financial wellbeing",
    hero_title_1: "Borrowing designed",
    hero_title_2: "around real life.",
    hero_body:
      "ARTHA checks whether a repayment fits your cash flow before it ever suggests a product.",
    hero_cta_twin: "See your affordability",
    hero_cta_needs: "Start with your needs",
    hero_privacy_link: "How your data is used",
    todays_decision: "Today's decision",
    checking: "Checking",
    preparing: "Understanding your cash flow…",
    preparing_body: "We are preparing an explanation you can understand.",
    structured_for_you: "Structured for you",
    per_month: "per month",
    months: "months",
    never_push: "We will never push a product that does not fit.",
    demo_scenario: "Demo scenario",
    demo_reset: "Reset demo",
    demo_reset_hint: "Clears the contact history the demo itself built up, so the Gate is judging the customer rather than your clicking.",
    home_heading: "A clear answer, before you commit.",
    loading: "Preparing your ARTHA view…",
    switching: "Re-running the decision for this customer…",
    footer_line:
      "We do not maximise how much you borrow. We maximise the chance that you keep paying.",
    footer_note: "Concept prototype · synthetic data only",

    // provenance
    provenance_chip: "Synthetic demo data",
    provenance_title: "Where these numbers come from",
    provenance_body:
      "Every rupee amount, probability and date in this app is generated by a synthetic transaction generator. No real customer data is used anywhere, and none of these figures is a measured result from a real portfolio.",
    close: "Close",

    // request
    request_title: "How much do you need?",
    request_body:
      "Tell us the amount you have in mind. We test that exact amount against your cash flow — and if it does not fit, we tell you the amount that does.",
    request_label: "Amount you want to borrow",
    request_submit: "Check this amount",
    request_clear: "Clear",
    request_hint: "Between ₹5,000 and ₹20,00,000.",
    request_invalid: "Enter an amount between ₹5,000 and ₹20,00,000.",
    request_active: "Testing your requested amount",

    // money / general
    your_money: "Your money",
    balance: "Balance",
    safe_buffer: "Safety buffer",
    this_month: "This month",
    what_we_offer: "What we are offering",
    what_we_dont: "What we are not offering — and why",
    see_why: "See why",

    // affordability
    affordability: "Can you carry this?",
    afford_what_title: "What affordability means here",
    afford_what_body:
      "Not whether you qualify on paper. Affordability here means: after this repayment leaves your account every month, does enough stay behind to absorb a late payday, an illness or a festival — without you falling below your safety buffer?",
    afford_why_graph_title: "Why a graph, and not a score",
    afford_why_graph_body:
      "A ratio tells you nothing about when you run short. The line below is your own projected balance day by day for the next six months, simulated thousands of times over. The second line is the same six months with this repayment taken out. The gap between them is what this loan actually costs you, and the dotted line is the level you should never drop below.",
    afford_read_title: "How to read your own lines",
    afford_read_1: "Follow the lower line. If it stays above the dotted buffer, the repayment fits.",
    afford_read_2: "Watch the dips. Each one is a month where money leaves before it arrives.",
    afford_read_3: "The shaded band is the unlucky case — not the average one.",
    afford_verdict: "What this means for you",
    afford_clears: "Across the stress tests below, your projected balance stays above your safety buffer.",
    afford_fragile: "Month to month this works. It stops working if one of the tests below happens.",
    afford_breaches: "On the projection as it stands, your balance drops below your safety buffer.",
    afford_shocks: "Late paydays in a row you could absorb",
    afford_shocks_note: "The stress tests below each apply one setback to your normal month. This counts something harder: how many income arrivals could fail one after another before your buffer breaks.",
    afford_scenarios: "If things go wrong",
    afford_lowest: "Lowest your balance would go",
    afford_stays_above: "you stay above",
    afford_falls_below: "you fall below",
    afford_no_obligation_title: "Nothing is being proposed right now",
    afford_no_obligation_body:
      "There is no repayment to test, so the chart below is simply your projected balance as things stand. It is here so you can see your own runway, not because we are asking you for anything.",
    afford_structure_works: "A structure that would work",

    // actions
    agree: "I agree",
    not_now: "Not now",
    disagree: "I disagree with this decision",
    human_review: "A person will review it",
    agree_recorded: "Recorded. The Key Facts are next — read them before you confirm anything.",
    not_now_recorded:
      "That is fine. Saying no is never recorded as a risk signal, and we will not ask again soon.",
    disagree_recorded:
      "Your disagreement is recorded and a person will review this decision. You do not need to do anything else.",
    disagree_help:
      "Use this if you believe the decision is wrong. It goes to a human reviewer with the full reasoning, not back to the same automated check.",
    back_to_overview: "Back to overview",

    // key facts
    key_facts: "Key facts",
    read_aloud: "Read this aloud",
    kfs_numbers: "The numbers",
    kfs_tenure: "What a longer tenure really costs",
    kfs_months: "Months",
    kfs_every_month: "Every month",
    kfs_extra: "Extra in total",
    kfs_warn:
      "A smaller monthly payment is not a smaller loan. The last column is what the extra months cost you.",
    kfs_note:
      "Key Fact Statement content and format must be verified against the current RBI Digital Lending Directions before any live use.",
    kfs_none_title: "There is no offer to read out yet",
    kfs_none_body:
      "A Key Fact Statement only exists once there is a specific amount, rate and repayment on the table. Nothing is being offered to you right now, so there is nothing here to agree to.",
    kfs_none_action: "Tell us what you need",

    // privacy
    privacy: "Your data",
    data_used: "Used",
    data_not_used: "Explicitly not used",
    revoke: "Turn off",

    // voice
    tap_to_speak: "Tap to speak",
    listening: "Listening…",
    stop_listening: "Stop",
    voice_unsupported:
      "This browser cannot listen. Type or pick a request below instead — the rest of the journey is identical.",
    voice_demo_transcript: "Demo transcript",
    voice_use_request: "Use this request",
    voice_low_confidence: "Test a low-confidence line",

    // recovery / empty
    safety_phrase: "Your safety phrase",
    never_ask: "We will never ask for your OTP, PIN or CVV",
    recovery_title: "We are with you",
    recovery_body: "We are not selling you anything new this month.",
    talk_to_person: "Talk to a person",
    nothing_today: "Nothing to tell you today",
    nothing_today_body:
      "Nothing has changed that we need to talk to you about. That is the system working.",

    // arrears
    arrears_title: "Your instalment",
    arrears_up_to_date: "Up to date",
    arrears_days_past_due: "days past due",
    arrears_missed: "instalment(s) outstanding",
  },

  hi: {
    nav_home: "सारांश",
    nav_twin: "वहनीयता",
    nav_assistant: "आवाज़ सहायक",
    nav_kfs: "मुख्य तथ्य",
    nav_privacy: "डेटा और निजता",
    brand_tagline: "बैंकिंग जो इंसानी बनी रहे",
    utility_left: "ARTHA · उपयुक्तता-पहले ऋण",
    utility_right: "यहाँ दिया हर आँकड़ा केवल उदाहरण है",
    hero_eyebrow: "आपकी आर्थिक भलाई",
    hero_title_1: "उधार, जो बनाया गया है",
    hero_title_2: "असल ज़िंदगी के हिसाब से।",
    hero_body:
      "ARTHA पहले यह जाँचता है कि किस्त आपके नकदी प्रवाह में बैठती है या नहीं — उसके बाद ही कोई उत्पाद सुझाता है।",
    hero_cta_twin: "अपनी वहनीयता देखें",
    hero_cta_needs: "अपनी ज़रूरत से शुरू करें",
    hero_privacy_link: "आपका डेटा कैसे उपयोग होता है",
    todays_decision: "आज का निर्णय",
    checking: "जाँच रहे हैं",
    preparing: "आपका नकदी प्रवाह समझ रहे हैं…",
    preparing_body: "हम ऐसा स्पष्टीकरण तैयार कर रहे हैं जो आपको समझ आए।",
    structured_for_you: "आपके लिए बनाया गया",
    per_month: "हर महीने",
    months: "महीने",
    never_push: "जो आपके लिए ठीक नहीं, वह हम कभी नहीं थोपेंगे।",
    demo_scenario: "डेमो परिदृश्य",
    demo_reset: "डेमो रीसेट करें",
    demo_reset_hint: "डेमो के दौरान बना संपर्क इतिहास मिटाता है, ताकि गेट आपकी क्लिक नहीं, ग्राहक की स्थिति परखे।",
    home_heading: "प्रतिबद्ध होने से पहले, एक साफ़ जवाब।",
    loading: "आपका ARTHA दृश्य तैयार हो रहा है…",
    switching: "इस ग्राहक के लिए निर्णय दोबारा चलाया जा रहा है…",
    footer_line:
      "हम यह अधिकतम नहीं करते कि आप कितना उधार लें। हम यह अधिकतम करते हैं कि आप चुकाते रहें।",
    footer_note: "अवधारणा प्रोटोटाइप · केवल कृत्रिम डेटा",

    provenance_chip: "कृत्रिम डेमो डेटा",
    provenance_title: "ये आँकड़े कहाँ से आते हैं",
    provenance_body:
      "इस ऐप का हर रुपया, हर संभावना और हर तारीख़ एक कृत्रिम लेन-देन जनरेटर से बनी है। कहीं भी किसी असली ग्राहक का डेटा उपयोग नहीं हुआ, और इनमें से कोई आँकड़ा किसी वास्तविक पोर्टफ़ोलियो का मापा गया परिणाम नहीं है।",
    close: "बंद करें",

    request_title: "आपको कितनी राशि चाहिए?",
    request_body:
      "जो राशि आपके मन में है वह बताइए। हम उसी राशि को आपके नकदी प्रवाह पर जाँचते हैं — और अगर वह नहीं बैठती, तो बताते हैं कि कौन-सी राशि बैठेगी।",
    request_label: "आप कितना उधार लेना चाहते हैं",
    request_submit: "यह राशि जाँचें",
    request_clear: "हटाएँ",
    request_hint: "₹5,000 से ₹20,00,000 के बीच।",
    request_invalid: "₹5,000 से ₹20,00,000 के बीच राशि डालें।",
    request_active: "आपकी माँगी गई राशि जाँची जा रही है",

    your_money: "आपका पैसा",
    balance: "बैलेंस",
    safe_buffer: "सुरक्षा बफ़र",
    this_month: "इस महीने",
    what_we_offer: "हम क्या दे रहे हैं",
    what_we_dont: "हम क्या नहीं दे रहे — और क्यों",
    see_why: "कारण देखें",

    affordability: "क्या आप इसे संभाल सकते हैं",
    afford_what_title: "यहाँ वहनीयता का क्या अर्थ है",
    afford_what_body:
      "यह नहीं कि काग़ज़ पर आप पात्र हैं या नहीं। यहाँ वहनीयता का अर्थ है: हर महीने यह किस्त कटने के बाद इतना बचता है या नहीं कि देर से आई तनख़्वाह, बीमारी या त्योहार झेला जा सके — और आप अपने सुरक्षा बफ़र से नीचे न जाएँ।",
    afford_why_graph_title: "अंक नहीं, ग्राफ़ क्यों",
    afford_why_graph_body:
      "कोई अनुपात यह नहीं बताता कि आपके पास पैसे कब कम पड़ेंगे। नीचे की रेखा अगले छह महीनों का आपका अपना अनुमानित बैलेंस है, दिन-प्रतिदिन, हज़ारों बार सिमुलेट किया हुआ। दूसरी रेखा वही छह महीने हैं, इस किस्त के कटने के बाद। दोनों के बीच का अंतर ही इस ऋण की असली क़ीमत है, और बिंदुदार रेखा वह स्तर है जिससे नीचे आपको कभी नहीं जाना चाहिए।",
    afford_read_title: "अपनी रेखाएँ कैसे पढ़ें",
    afford_read_1:
      "नीचे वाली रेखा देखिए। अगर वह बिंदुदार बफ़र से ऊपर रहती है, तो किस्त बैठती है।",
    afford_read_2:
      "गिरावटों पर ध्यान दीजिए। हर गिरावट वह महीना है जब पैसा आने से पहले निकल जाता है।",
    afford_read_3: "छायांकित पट्टी बुरे दिन की स्थिति है — औसत स्थिति नहीं।",
    afford_verdict: "आपके लिए इसका क्या मतलब है",
    afford_clears: "नीचे दिए गए सभी परीक्षणों में आपका अनुमानित बैलेंस सुरक्षा बफ़र से ऊपर रहता है।",
    afford_fragile: "महीने-दर-महीने यह चल जाएगा। नीचे दिए किसी एक हालात में यह नहीं चलेगा।",
    afford_breaches: "मौजूदा अनुमान पर आपका बैलेंस सुरक्षा बफ़र से नीचे चला जाता है।",
    afford_shocks: "लगातार कितनी बार आमदनी में देरी झेल सकते हैं",
    afford_shocks_note: "नीचे दिए परीक्षण आपके सामान्य महीने पर एक-एक झटका लगाते हैं। यह उससे कठिन बात गिनता है: लगातार कितनी बार आमदनी न आए तो भी आपका बफ़र टिका रहे।",
    afford_scenarios: "अगर कुछ ग़लत हो जाए",
    afford_lowest: "आपका बैलेंस कम से कम कितना होगा",
    afford_stays_above: "आप ऊपर बने रहते हैं",
    afford_falls_below: "आप नीचे चले जाते हैं",
    afford_no_obligation_title: "अभी कुछ भी प्रस्तावित नहीं है",
    afford_no_obligation_body:
      "जाँचने के लिए कोई किस्त नहीं है, इसलिए नीचे का ग्राफ़ बस आपका अनुमानित बैलेंस दिखाता है। यह इसलिए है कि आप अपनी स्थिति देख सकें, इसलिए नहीं कि हम आपसे कुछ माँग रहे हैं।",
    afford_structure_works: "ऐसी संरचना जो काम करेगी",

    agree: "मैं सहमत हूँ",
    not_now: "अभी नहीं",
    disagree: "मैं इस निर्णय से असहमत हूँ",
    human_review: "एक व्यक्ति इसकी समीक्षा करेगा",
    agree_recorded:
      "दर्ज कर लिया गया। अब मुख्य तथ्य पढ़िए — पुष्टि करने से पहले उन्हें ज़रूर पढ़ें।",
    not_now_recorded:
      "कोई बात नहीं। मना करना कभी जोखिम संकेत नहीं माना जाता, और हम जल्दी दोबारा नहीं पूछेंगे।",
    disagree_recorded:
      "आपकी असहमति दर्ज हो गई है और एक व्यक्ति इस निर्णय की समीक्षा करेगा। आपको और कुछ नहीं करना है।",
    disagree_help:
      "अगर आपको लगता है कि निर्णय ग़लत है तो इसका उपयोग करें। यह पूरे कारणों के साथ एक व्यक्ति के पास जाता है, उसी स्वचालित जाँच के पास वापस नहीं।",
    back_to_overview: "सारांश पर लौटें",

    key_facts: "मुख्य तथ्य",
    read_aloud: "पढ़कर सुनाएँ",
    kfs_numbers: "आँकड़े",
    kfs_tenure: "लंबी अवधि की असली क़ीमत",
    kfs_months: "महीने",
    kfs_every_month: "हर महीने",
    kfs_extra: "कुल मिलाकर अतिरिक्त",
    kfs_warn:
      "छोटी मासिक किस्त का मतलब छोटा ऋण नहीं है। आख़िरी स्तंभ बताता है कि अतिरिक्त महीने आपको क्या पड़ते हैं।",
    kfs_note:
      "मुख्य तथ्य विवरण की सामग्री और प्रारूप को किसी भी वास्तविक उपयोग से पहले मौजूदा RBI डिजिटल लेंडिंग निर्देशों से सत्यापित करना आवश्यक है।",
    kfs_none_title: "अभी पढ़ने के लिए कोई प्रस्ताव नहीं है",
    kfs_none_body:
      "मुख्य तथ्य विवरण तभी बनता है जब कोई निश्चित राशि, दर और किस्त सामने हो। अभी आपको कुछ भी प्रस्तावित नहीं है, इसलिए यहाँ सहमत होने लायक कुछ नहीं है।",
    kfs_none_action: "बताइए आपको क्या चाहिए",

    privacy: "आपका डेटा",
    data_used: "उपयोग किया गया",
    data_not_used: "उपयोग नहीं किया गया",
    revoke: "बंद करें",

    tap_to_speak: "बोलने के लिए दबाएँ",
    listening: "सुन रहे हैं…",
    stop_listening: "रोकें",
    voice_unsupported:
      "यह ब्राउज़र सुन नहीं सकता। नीचे लिखकर या कोई अनुरोध चुनकर आगे बढ़िए — बाक़ी यात्रा बिल्कुल वही रहेगी।",
    voice_demo_transcript: "डेमो प्रतिलेख",
    voice_use_request: "यह अनुरोध भेजें",
    voice_low_confidence: "कम-भरोसे वाली पंक्ति जाँचें",

    safety_phrase: "आपका सुरक्षा वाक्यांश",
    never_ask: "हम कभी OTP, PIN या CVV नहीं मांगेंगे",
    recovery_title: "हम आपके साथ हैं",
    recovery_body: "इस महीने हम आपको कुछ नया नहीं बेच रहे।",
    talk_to_person: "किसी व्यक्ति से बात करें",
    nothing_today: "आज बताने लायक कुछ नहीं है",
    nothing_today_body:
      "कुछ भी ऐसा नहीं बदला जिस पर बात करनी ज़रूरी हो। यह सही काम कर रहा है।",

    arrears_title: "आपकी किस्त",
    arrears_up_to_date: "समय पर",
    arrears_days_past_due: "दिन बकाया",
    arrears_missed: "किस्तें बकाया",
  },

  mr: {
    nav_home: "आढावा",
    nav_twin: "परवडणारे आहे का",
    nav_assistant: "आवाज मार्गदर्शक",
    nav_kfs: "मुख्य तथ्ये",
    nav_privacy: "डेटा आणि गोपनीयता",
    brand_tagline: "माणुसकी टिकवणारी बँकिंग",
    utility_left: "ARTHA · योग्यता-प्रथम कर्ज",
    utility_right: "इथला प्रत्येक आकडा केवळ उदाहरण आहे",
    hero_eyebrow: "तुमचे आर्थिक स्वास्थ्य",
    hero_title_1: "खऱ्या आयुष्याचा विचार करून",
    hero_title_2: "रचलेले कर्ज.",
    hero_body:
      "कोणतेही उत्पादन सुचवण्याआधी ARTHA तपासते की हप्ता तुमच्या रोख प्रवाहात बसतो का.",
    hero_cta_twin: "तुम्हाला परवडते का पहा",
    hero_cta_needs: "तुमच्या गरजेपासून सुरुवात करा",
    hero_privacy_link: "तुमचा डेटा कसा वापरला जातो",
    todays_decision: "आजचा निर्णय",
    checking: "तपासत आहोत",
    preparing: "तुमचा रोख प्रवाह समजून घेत आहोत…",
    preparing_body: "तुम्हाला समजेल असे स्पष्टीकरण आम्ही तयार करत आहोत.",
    structured_for_you: "तुमच्यासाठी रचलेले",
    per_month: "दर महिना",
    months: "महिने",
    never_push: "जे तुम्हाला झेपणार नाही ते आम्ही कधीही लादणार नाही.",
    demo_scenario: "डेमो परिस्थिती",
    demo_reset: "डेमो रीसेट करा",
    demo_reset_hint: "डेमोदरम्यान जमा झालेला संपर्क इतिहास पुसतो, म्हणजे गेट तुमच्या क्लिकवर नव्हे तर ग्राहकावर निर्णय घेते.",
    home_heading: "वचन देण्याआधी, एक स्पष्ट उत्तर.",
    loading: "तुमचे ARTHA दृश्य तयार होत आहे…",
    switching: "या ग्राहकासाठी निर्णय पुन्हा चालवत आहोत…",
    footer_line:
      "तुम्ही किती कर्ज घेता ते आम्ही वाढवत नाही. तुम्ही परतफेड करत राहाल याची शक्यता आम्ही वाढवतो.",
    footer_note: "संकल्पना नमुना · केवळ कृत्रिम डेटा",

    provenance_chip: "कृत्रिम डेमो डेटा",
    provenance_title: "हे आकडे कुठून येतात",
    provenance_body:
      "या अ‍ॅपमधील प्रत्येक रुपया, शक्यता आणि तारीख कृत्रिम व्यवहार जनरेटरने तयार केली आहे. कुठेही खऱ्या ग्राहकाचा डेटा वापरलेला नाही, आणि यापैकी कोणताही आकडा खऱ्या पोर्टफोलिओचा मोजलेला निकाल नाही.",
    close: "बंद करा",

    request_title: "तुम्हाला किती रक्कम हवी आहे?",
    request_body:
      "तुमच्या मनात असलेली रक्कम सांगा. तीच रक्कम आम्ही तुमच्या रोख प्रवाहावर तपासतो — आणि ती बसत नसेल, तर कोणती बसेल ते सांगतो.",
    request_label: "तुम्हाला किती कर्ज हवे आहे",
    request_submit: "ही रक्कम तपासा",
    request_clear: "काढून टाका",
    request_hint: "₹5,000 ते ₹20,00,000 दरम्यान.",
    request_invalid: "₹5,000 ते ₹20,00,000 दरम्यान रक्कम टाका.",
    request_active: "तुम्ही मागितलेली रक्कम तपासली जात आहे",

    your_money: "तुमचे पैसे",
    balance: "शिल्लक",
    safe_buffer: "सुरक्षा राखीव",
    this_month: "या महिन्यात",
    what_we_offer: "आम्ही काय देत आहोत",
    what_we_dont: "आम्ही काय देत नाही — आणि का",
    see_why: "कारण पहा",

    affordability: "हे तुम्हाला झेपेल का",
    afford_what_title: "इथे परवडणे म्हणजे काय",
    afford_what_body:
      "कागदावर तुम्ही पात्र आहात का, हा प्रश्न नाही. इथे परवडणे म्हणजे: दर महिन्याला हा हप्ता गेल्यावर उशिरा आलेला पगार, आजारपण किंवा सण पेलण्याइतके पैसे मागे राहतात का — आणि तुम्ही सुरक्षा राखीवाच्या खाली जात नाही ना.",
    afford_why_graph_title: "गुण नव्हे, आलेख का",
    afford_why_graph_body:
      "कोणतेही गुणोत्तर तुम्हाला हे सांगत नाही की पैसे कधी कमी पडतील. खालची रेषा म्हणजे पुढील सहा महिन्यांतील तुमची स्वतःची अपेक्षित शिल्लक, दिवसागणिक, हजारो वेळा सिम्युलेट केलेली. दुसरी रेषा तेच सहा महिने आहेत, पण हा हप्ता वजा करून. दोन रेषांमधील अंतर हेच या कर्जाची खरी किंमत आहे, आणि ठिपक्यांची रेषा म्हणजे ज्याखाली तुम्ही कधीही जाऊ नये अशी पातळी.",
    afford_read_title: "तुमच्या रेषा कशा वाचायच्या",
    afford_read_1:
      "खालची रेषा पहा. ती ठिपक्यांच्या राखीवाच्या वर राहत असेल, तर हप्ता बसतो.",
    afford_read_2:
      "घसरणींकडे लक्ष द्या. प्रत्येक घसरण म्हणजे पैसे येण्याआधीच जाणारा महिना.",
    afford_read_3: "छायांकित पट्टा हा वाईट परिस्थितीचा आहे — सरासरीचा नाही.",
    afford_verdict: "तुमच्यासाठी याचा अर्थ काय",
    afford_clears: "खालील सर्व चाचण्यांमध्ये तुमची अपेक्षित शिल्लक सुरक्षा राखीवाच्या वर राहते.",
    afford_fragile: "महिन्या-महिन्याने हे चालेल. खालीलपैकी एखादी गोष्ट घडल्यास चालणार नाही.",
    afford_breaches: "सध्याच्या अंदाजानुसार तुमची शिल्लक सुरक्षा राखीवाच्या खाली जाते.",
    afford_shocks: "सलग किती वेळा उत्पन्न उशिरा आले तरी चालेल",
    afford_shocks_note: "खालील चाचण्या तुमच्या सामान्य महिन्यावर एक-एक धक्का लावतात. हे त्याहून कठीण गोष्ट मोजते: सलग किती वेळा उत्पन्न आले नाही तरी तुमचा राखीव टिकेल.",
    afford_scenarios: "काही बिघडले तर",
    afford_lowest: "तुमची शिल्लक किमान किती होईल",
    afford_stays_above: "तुम्ही वर राहता",
    afford_falls_below: "तुम्ही खाली जाता",
    afford_no_obligation_title: "सध्या काहीही प्रस्तावित नाही",
    afford_no_obligation_body:
      "तपासण्यासाठी कोणताही हप्ता नाही, त्यामुळे खालील आलेख फक्त तुमची अपेक्षित शिल्लक दाखवतो. तुम्हाला तुमची स्थिती दिसावी म्हणून तो इथे आहे, आम्ही तुमच्याकडे काही मागत आहोत म्हणून नाही.",
    afford_structure_works: "अशी रचना जी चालेल",

    agree: "मी सहमत आहे",
    not_now: "आत्ता नको",
    disagree: "मी या निर्णयाशी असहमत आहे",
    human_review: "एक व्यक्ती याची तपासणी करेल",
    agree_recorded:
      "नोंदवले. आता मुख्य तथ्ये आहेत — काहीही निश्चित करण्याआधी ती वाचा.",
    not_now_recorded:
      "ठीक आहे. नकार कधीही जोखमीचा संकेत मानला जात नाही, आणि आम्ही लवकर पुन्हा विचारणार नाही.",
    disagree_recorded:
      "तुमची असहमती नोंदवली आहे आणि एक व्यक्ती या निर्णयाची तपासणी करेल. तुम्हाला आणखी काही करायची गरज नाही.",
    disagree_help:
      "निर्णय चुकीचा वाटत असेल तर हे वापरा. हे पूर्ण कारणांसह माणसाकडे जाते, त्याच स्वयंचलित तपासणीकडे परत नाही.",
    back_to_overview: "आढाव्याकडे परत",

    key_facts: "मुख्य तथ्ये",
    read_aloud: "मोठ्याने वाचून दाखवा",
    kfs_numbers: "आकडे",
    kfs_tenure: "जास्त मुदतीची खरी किंमत",
    kfs_months: "महिने",
    kfs_every_month: "दर महिना",
    kfs_extra: "एकूण जादा",
    kfs_warn:
      "कमी मासिक हप्ता म्हणजे कमी कर्ज नव्हे. शेवटचा स्तंभ म्हणजे जादा महिन्यांची किंमत.",
    kfs_note:
      "मुख्य तथ्य विवरणाची मांडणी आणि मजकूर कोणत्याही प्रत्यक्ष वापराआधी सध्याच्या RBI डिजिटल लेंडिंग निर्देशांशी पडताळणे आवश्यक आहे.",
    kfs_none_title: "सध्या वाचण्यासाठी कोणताही प्रस्ताव नाही",
    kfs_none_body:
      "निश्चित रक्कम, दर आणि हप्ता समोर असेल तरच मुख्य तथ्य विवरण तयार होते. सध्या तुम्हाला काहीही देऊ केलेले नाही, त्यामुळे इथे सहमत होण्यासारखे काही नाही.",
    kfs_none_action: "तुम्हाला काय हवे ते सांगा",

    privacy: "तुमचा डेटा",
    data_used: "वापरलेले",
    data_not_used: "स्पष्टपणे न वापरलेले",
    revoke: "बंद करा",

    tap_to_speak: "बोलण्यासाठी दाबा",
    listening: "ऐकत आहोत…",
    stop_listening: "थांबवा",
    voice_unsupported:
      "हा ब्राउझर ऐकू शकत नाही. खाली लिहा किंवा एखादी विनंती निवडा — पुढचा प्रवास तसाच राहील.",
    voice_demo_transcript: "डेमो उतारा",
    voice_use_request: "ही विनंती वापरा",
    voice_low_confidence: "कमी खात्रीची ओळ तपासा",

    safety_phrase: "तुमचा सुरक्षा वाक्यांश",
    never_ask: "आम्ही कधीही OTP, PIN किंवा CVV मागणार नाही",
    recovery_title: "आम्ही तुमच्यासोबत आहोत",
    recovery_body: "या महिन्यात आम्ही तुम्हाला काहीही नवीन विकत नाही आहोत.",
    talk_to_person: "एखाद्या व्यक्तीशी बोला",
    nothing_today: "आज सांगण्यासारखे काही नाही",
    nothing_today_body:
      "बोलण्याची गरज पडेल असे काहीही बदललेले नाही. हीच व्यवस्था नीट चालल्याची खूण आहे.",

    arrears_title: "तुमचा हप्ता",
    arrears_up_to_date: "वेळेवर",
    arrears_days_past_due: "दिवस थकीत",
    arrears_missed: "हप्ते थकीत",
  },

  ta: {
    nav_home: "சுருக்கம்",
    nav_twin: "தாங்க முடியுமா",
    nav_assistant: "குரல் வழிகாட்டி",
    nav_kfs: "முக்கிய தகவல்கள்",
    nav_privacy: "தரவும் தனியுரிமையும்",
    brand_tagline: "மனிதத்தன்மை மாறாத வங்கிச் சேவை",
    utility_left: "ARTHA · பொருத்தம் முதன்மையான கடன்",
    utility_right: "இங்குள்ள ஒவ்வொரு எண்ணும் எடுத்துக்காட்டு மட்டுமே",
    hero_eyebrow: "உங்கள் நிதி நலன்",
    hero_title_1: "நிஜ வாழ்க்கையை மையமாக",
    hero_title_2: "வைத்து வடிவமைத்த கடன்.",
    hero_body:
      "எந்தத் தயாரிப்பையும் பரிந்துரைப்பதற்கு முன், தவணை உங்கள் பணப்புழக்கத்தில் பொருந்துகிறதா என்பதை ARTHA சரிபார்க்கிறது.",
    hero_cta_twin: "உங்களால் தாங்க முடியுமா பாருங்கள்",
    hero_cta_needs: "உங்கள் தேவையிலிருந்து தொடங்குங்கள்",
    hero_privacy_link: "உங்கள் தரவு எப்படிப் பயன்படுகிறது",
    todays_decision: "இன்றைய முடிவு",
    checking: "சரிபார்க்கிறோம்",
    preparing: "உங்கள் பணப்புழக்கத்தைப் புரிந்துகொள்கிறோம்…",
    preparing_body: "உங்களுக்குப் புரியும் விளக்கத்தை நாங்கள் தயாரிக்கிறோம்.",
    structured_for_you: "உங்களுக்காக வடிவமைக்கப்பட்டது",
    per_month: "மாதம் ஒன்றுக்கு",
    months: "மாதங்கள்",
    never_push: "உங்களுக்குப் பொருந்தாத எதையும் நாங்கள் ஒருபோதும் திணிக்க மாட்டோம்.",
    demo_scenario: "டெமோ சூழல்",
    demo_reset: "டெமோவை மீட்டமை",
    demo_reset_hint: "டெமோ உருவாக்கிய தொடர்பு வரலாற்றை அழிக்கிறது, அதனால் கேட் உங்கள் கிளிக்கை அல்ல, வாடிக்கையாளரை மதிப்பிடும்.",
    home_heading: "உறுதியளிப்பதற்கு முன், ஒரு தெளிவான பதில்.",
    loading: "உங்கள் ARTHA காட்சி தயாராகிறது…",
    switching: "இந்த வாடிக்கையாளருக்கான முடிவு மீண்டும் இயக்கப்படுகிறது…",
    footer_line:
      "நீங்கள் எவ்வளவு கடன் வாங்குகிறீர்கள் என்பதை நாங்கள் அதிகரிப்பதில்லை. நீங்கள் தொடர்ந்து திருப்பிச் செலுத்தும் வாய்ப்பை அதிகரிக்கிறோம்.",
    footer_note: "கருத்து மாதிரி · செயற்கைத் தரவு மட்டுமே",

    provenance_chip: "செயற்கை டெமோ தரவு",
    provenance_title: "இந்த எண்கள் எங்கிருந்து வருகின்றன",
    provenance_body:
      "இந்த செயலியில் உள்ள ஒவ்வொரு ரூபாயும், நிகழ்தகவும், தேதியும் ஒரு செயற்கைப் பரிவர்த்தனை உருவாக்கியால் உருவாக்கப்பட்டவை. உண்மையான வாடிக்கையாளர் தரவு எங்கும் பயன்படுத்தப்படவில்லை, இந்த எண்கள் எதுவும் உண்மையான கடன் தொகுப்பிலிருந்து அளக்கப்பட்ட முடிவு அல்ல.",
    close: "மூடு",

    request_title: "உங்களுக்கு எவ்வளவு தேவை?",
    request_body:
      "நீங்கள் நினைக்கும் தொகையைச் சொல்லுங்கள். அதே தொகையை உங்கள் பணப்புழக்கத்தில் சரிபார்க்கிறோம் — பொருந்தவில்லை என்றால், எந்தத் தொகை பொருந்தும் என்பதைச் சொல்கிறோம்.",
    request_label: "நீங்கள் கடனாகப் பெற விரும்பும் தொகை",
    request_submit: "இந்தத் தொகையைச் சரிபார்",
    request_clear: "அழி",
    request_hint: "₹5,000 முதல் ₹20,00,000 வரை.",
    request_invalid: "₹5,000 முதல் ₹20,00,000 வரையிலான தொகையை உள்ளிடுங்கள்.",
    request_active: "நீங்கள் கேட்ட தொகை சரிபார்க்கப்படுகிறது",

    your_money: "உங்கள் பணம்",
    balance: "இருப்பு",
    safe_buffer: "பாதுகாப்பு இருப்பு",
    this_month: "இந்த மாதம்",
    what_we_offer: "நாங்கள் என்ன வழங்குகிறோம்",
    what_we_dont: "நாங்கள் என்ன வழங்கவில்லை — ஏன்",
    see_why: "காரணம் பார்",

    affordability: "இதை உங்களால் தாங்க முடியுமா",
    afford_what_title: "இங்கே தாங்கும் திறன் என்றால் என்ன",
    afford_what_body:
      "காகிதத்தில் நீங்கள் தகுதியானவரா என்பதல்ல. இங்கே தாங்கும் திறன் என்பது: ஒவ்வொரு மாதமும் இந்தத் தவணை போனபிறகு, தாமதமான சம்பளம், நோய் அல்லது பண்டிகையைச் சமாளிக்கும் அளவு பணம் மிச்சம் இருக்கிறதா — நீங்கள் உங்கள் பாதுகாப்பு இருப்புக்குக் கீழே செல்லாமல்.",
    afford_why_graph_title: "மதிப்பெண் அல்ல, வரைபடம் ஏன்",
    afford_why_graph_body:
      "எந்த விகிதமும் பணம் எப்போது பற்றாக்குறையாகும் என்பதைச் சொல்வதில்லை. கீழே உள்ள கோடு அடுத்த ஆறு மாதங்களுக்கான உங்கள் சொந்த மதிப்பிடப்பட்ட இருப்பு, நாள்தோறும், ஆயிரக்கணக்கான முறை உருவகப்படுத்தப்பட்டது. இரண்டாவது கோடு அதே ஆறு மாதங்கள், ஆனால் இந்தத் தவணை கழிக்கப்பட்ட பிறகு. இரண்டுக்கும் இடையிலான இடைவெளிதான் இந்தக் கடனின் உண்மையான விலை; புள்ளிக் கோடு நீங்கள் எப்போதும் கீழே செல்லக் கூடாத நிலை.",
    afford_read_title: "உங்கள் கோடுகளை எப்படிப் படிப்பது",
    afford_read_1:
      "கீழ்க்கோட்டைப் பின்தொடருங்கள். அது புள்ளிக் கோட்டுக்கு மேலே இருந்தால், தவணை பொருந்துகிறது.",
    afford_read_2:
      "இறக்கங்களைக் கவனியுங்கள். ஒவ்வொன்றும் பணம் வருவதற்கு முன்பே செலவாகும் மாதம்.",
    afford_read_3: "நிழலிடப்பட்ட பகுதி மோசமான சூழ்நிலை — சராசரி அல்ல.",
    afford_verdict: "இது உங்களுக்கு என்ன அர்த்தம்",
    afford_clears: "கீழே உள்ள அனைத்துச் சோதனைகளிலும் உங்கள் மதிப்பிடப்பட்ட இருப்பு பாதுகாப்பு நிலைக்கு மேலே இருக்கிறது.",
    afford_fragile: "மாதம் மாதம் இது சரியாக இருக்கும். கீழே உள்ள ஒன்று நடந்தால் சரியாக இருக்காது.",
    afford_breaches: "தற்போதைய மதிப்பீட்டின்படி உங்கள் இருப்பு பாதுகாப்பு நிலைக்குக் கீழே செல்கிறது.",
    afford_shocks: "தொடர்ச்சியாக எத்தனை முறை வருமானம் தவறினாலும் சமாளிக்க முடியும்",
    afford_shocks_note: "கீழே உள்ள சோதனைகள் உங்கள் வழக்கமான மாதத்தில் ஒரு பின்னடைவை மட்டும் சேர்க்கின்றன. இது அதைவிடக் கடினமானதை எண்ணுகிறது: தொடர்ச்சியாக எத்தனை முறை வருமானம் வராமல் போனாலும் உங்கள் பாதுகாப்பு நிலை தாங்கும்.",
    afford_scenarios: "ஏதாவது தவறாகப் போனால்",
    afford_lowest: "உங்கள் இருப்பு குறைந்தபட்சம் எவ்வளவு",
    afford_stays_above: "நீங்கள் மேலே இருக்கிறீர்கள்",
    afford_falls_below: "நீங்கள் கீழே செல்கிறீர்கள்",
    afford_no_obligation_title: "இப்போது எதுவும் முன்மொழியப்படவில்லை",
    afford_no_obligation_body:
      "சரிபார்க்க எந்தத் தவணையும் இல்லை, எனவே கீழே உள்ள வரைபடம் உங்கள் மதிப்பிடப்பட்ட இருப்பை மட்டுமே காட்டுகிறது. உங்கள் நிலையை நீங்கள் பார்க்கவே இது இங்கே, நாங்கள் ஏதாவது கேட்பதால் அல்ல.",
    afford_structure_works: "வேலை செய்யும் ஒரு அமைப்பு",

    agree: "நான் ஒப்புக்கொள்கிறேன்",
    not_now: "இப்போது வேண்டாம்",
    disagree: "இந்த முடிவை நான் ஏற்கவில்லை",
    human_review: "ஒருவர் இதைப் பரிசீலிப்பார்",
    agree_recorded:
      "பதிவு செய்யப்பட்டது. அடுத்தது முக்கியத் தகவல்கள் — உறுதி செய்வதற்கு முன் அவற்றைப் படியுங்கள்.",
    not_now_recorded:
      "பரவாயில்லை. மறுப்பது ஒருபோதும் இடர் சமிக்ஞையாகப் பதிவு செய்யப்படுவதில்லை; விரைவில் மீண்டும் கேட்க மாட்டோம்.",
    disagree_recorded:
      "உங்கள் மறுப்பு பதிவாகியுள்ளது; ஒருவர் இந்த முடிவைப் பரிசீலிப்பார். நீங்கள் வேறு எதுவும் செய்யத் தேவையில்லை.",
    disagree_help:
      "முடிவு தவறு என நீங்கள் கருதினால் இதைப் பயன்படுத்துங்கள். இது முழுக் காரணங்களுடன் ஒரு மனிதரிடம் செல்கிறது, அதே தானியங்கிச் சோதனைக்கு அல்ல.",
    back_to_overview: "சுருக்கத்திற்குத் திரும்பு",

    key_facts: "முக்கிய தகவல்கள்",
    read_aloud: "படித்துக் காட்டு",
    kfs_numbers: "எண்கள்",
    kfs_tenure: "நீண்ட காலத்தின் உண்மையான விலை",
    kfs_months: "மாதங்கள்",
    kfs_every_month: "மாதந்தோறும்",
    kfs_extra: "மொத்தத்தில் கூடுதல்",
    kfs_warn:
      "சிறிய மாதத் தவணை என்பது சிறிய கடன் அல்ல. கடைசி நெடுவரிசை கூடுதல் மாதங்களின் விலை.",
    kfs_note:
      "முக்கியத் தகவல் அறிக்கையின் உள்ளடக்கமும் வடிவமும், நடைமுறைப் பயன்பாட்டுக்கு முன் தற்போதைய RBI டிஜிட்டல் கடன் வழிகாட்டுதல்களுடன் சரிபார்க்கப்பட வேண்டும்.",
    kfs_none_title: "இப்போது படிக்க எந்தச் சலுகையும் இல்லை",
    kfs_none_body:
      "குறிப்பிட்ட தொகை, வட்டி விகிதம், தவணை இருந்தால் மட்டுமே முக்கியத் தகவல் அறிக்கை உருவாகும். இப்போது உங்களுக்கு எதுவும் வழங்கப்படவில்லை, எனவே ஒப்புக்கொள்ள இங்கே எதுவும் இல்லை.",
    kfs_none_action: "உங்களுக்கு என்ன தேவை என்று சொல்லுங்கள்",

    privacy: "உங்கள் தரவு",
    data_used: "பயன்படுத்தப்பட்டது",
    data_not_used: "வெளிப்படையாகப் பயன்படுத்தப்படவில்லை",
    revoke: "நிறுத்து",

    tap_to_speak: "பேச அழுத்துங்கள்",
    listening: "கேட்கிறோம்…",
    stop_listening: "நிறுத்து",
    voice_unsupported:
      "இந்த உலாவியால் கேட்க முடியாது. கீழே தட்டச்சு செய்யுங்கள் அல்லது ஒரு கோரிக்கையைத் தேர்ந்தெடுங்கள் — மீதிப் பயணம் அப்படியே இருக்கும்.",
    voice_demo_transcript: "டெமோ உரை",
    voice_use_request: "இந்தக் கோரிக்கையைப் பயன்படுத்து",
    voice_low_confidence: "குறைந்த நம்பிக்கை வரியைச் சோதி",

    safety_phrase: "உங்கள் பாதுகாப்புச் சொற்றொடர்",
    never_ask: "OTP, PIN அல்லது CVV-ஐ நாங்கள் ஒருபோதும் கேட்க மாட்டோம்",
    recovery_title: "நாங்கள் உங்களுடன் இருக்கிறோம்",
    recovery_body: "இந்த மாதம் உங்களுக்குப் புதிதாக எதையும் விற்கவில்லை.",
    talk_to_person: "ஒருவரிடம் பேசுங்கள்",
    nothing_today: "இன்று சொல்ல ஒன்றுமில்லை",
    nothing_today_body:
      "பேச வேண்டிய அளவுக்கு எதுவும் மாறவில்லை. அமைப்பு சரியாக வேலை செய்கிறது என்பதற்கு இதுவே அடையாளம்.",

    arrears_title: "உங்கள் தவணை",
    arrears_up_to_date: "நிலுவை இல்லை",
    arrears_days_past_due: "நாட்கள் நிலுவை",
    arrears_missed: "தவணைகள் நிலுவையில்",
  },

  bn: {
    nav_home: "সারসংক্ষেপ",
    nav_twin: "সামলাতে পারবেন কি",
    nav_assistant: "কণ্ঠ সহায়ক",
    nav_kfs: "মূল তথ্য",
    nav_privacy: "তথ্য ও গোপনীয়তা",
    brand_tagline: "মানবিক থাকা ব্যাঙ্কিং",
    utility_left: "ARTHA · উপযুক্ততা-প্রথম ঋণ",
    utility_right: "এখানে প্রতিটি সংখ্যা কেবল উদাহরণ",
    hero_eyebrow: "আপনার আর্থিক সুস্থতা",
    hero_title_1: "সত্যিকারের জীবনকে ঘিরে",
    hero_title_2: "সাজানো ঋণ।",
    hero_body:
      "কোনো পণ্য প্রস্তাব করার আগে ARTHA দেখে নেয় কিস্তিটি আপনার নগদ প্রবাহে মেলে কি না।",
    hero_cta_twin: "আপনি সামলাতে পারবেন কি দেখুন",
    hero_cta_needs: "আপনার প্রয়োজন দিয়ে শুরু করুন",
    hero_privacy_link: "আপনার তথ্য কীভাবে ব্যবহৃত হয়",
    todays_decision: "আজকের সিদ্ধান্ত",
    checking: "যাচাই করছি",
    preparing: "আপনার নগদ প্রবাহ বোঝার চেষ্টা করছি…",
    preparing_body: "আপনি বুঝতে পারবেন এমন ব্যাখ্যা আমরা তৈরি করছি।",
    structured_for_you: "আপনার জন্য সাজানো",
    per_month: "প্রতি মাসে",
    months: "মাস",
    never_push: "আপনার জন্য যা মানানসই নয়, তা আমরা কখনও চাপিয়ে দেব না।",
    demo_scenario: "ডেমো পরিস্থিতি",
    demo_reset: "ডেমো রিসেট করুন",
    demo_reset_hint: "ডেমো চলাকালীন জমা হওয়া যোগাযোগের ইতিহাস মুছে দেয়, যাতে গেট আপনার ক্লিক নয়, গ্রাহককে বিচার করে।",
    home_heading: "প্রতিশ্রুতি দেওয়ার আগে, একটি স্পষ্ট উত্তর।",
    loading: "আপনার ARTHA দৃশ্য তৈরি হচ্ছে…",
    switching: "এই গ্রাহকের জন্য সিদ্ধান্ত আবার চালানো হচ্ছে…",
    footer_line:
      "আপনি কত ঋণ নেবেন তা আমরা বাড়াই না। আপনি যাতে শোধ করে যেতে পারেন, সেই সম্ভাবনা বাড়াই।",
    footer_note: "ধারণাগত নমুনা · কেবল কৃত্রিম তথ্য",

    provenance_chip: "কৃত্রিম ডেমো তথ্য",
    provenance_title: "এই সংখ্যাগুলি কোথা থেকে আসে",
    provenance_body:
      "এই অ্যাপের প্রতিটি টাকা, সম্ভাবনা ও তারিখ একটি কৃত্রিম লেনদেন জেনারেটর থেকে তৈরি। কোথাও কোনো প্রকৃত গ্রাহকের তথ্য ব্যবহার করা হয়নি, এবং এর কোনো সংখ্যাই প্রকৃত পোর্টফোলিও থেকে মাপা ফলাফল নয়।",
    close: "বন্ধ করুন",

    request_title: "আপনার কত টাকা দরকার?",
    request_body:
      "আপনার মনে থাকা অঙ্কটি বলুন। ঠিক সেই অঙ্কই আমরা আপনার নগদ প্রবাহে যাচাই করি — না মিললে কোন অঙ্ক মিলবে তা জানাই।",
    request_label: "আপনি কত ঋণ নিতে চান",
    request_submit: "এই অঙ্ক যাচাই করুন",
    request_clear: "মুছুন",
    request_hint: "₹5,000 থেকে ₹20,00,000 এর মধ্যে।",
    request_invalid: "₹5,000 থেকে ₹20,00,000 এর মধ্যে অঙ্ক দিন।",
    request_active: "আপনার চাওয়া অঙ্ক যাচাই করা হচ্ছে",

    your_money: "আপনার টাকা",
    balance: "ব্যালান্স",
    safe_buffer: "নিরাপত্তা সঞ্চয়",
    this_month: "এই মাসে",
    what_we_offer: "আমরা কী দিচ্ছি",
    what_we_dont: "আমরা কী দিচ্ছি না — এবং কেন",
    see_why: "কারণ দেখুন",

    affordability: "আপনি কি এটি সামলাতে পারবেন",
    afford_what_title: "এখানে সামর্থ্য বলতে কী বোঝায়",
    afford_what_body:
      "কাগজে আপনি যোগ্য কি না, সেটা নয়। এখানে সামর্থ্য মানে: প্রতি মাসে এই কিস্তি কেটে যাওয়ার পরেও দেরিতে আসা বেতন, অসুস্থতা বা উৎসব সামলানোর মতো যথেষ্ট টাকা থেকে যায় কি না — আপনার নিরাপত্তা সঞ্চয়ের নিচে না নেমে।",
    afford_why_graph_title: "স্কোর নয়, লেখচিত্র কেন",
    afford_why_graph_body:
      "কোনো অনুপাত বলে না কখন আপনার টাকা কম পড়বে। নিচের রেখাটি আগামী ছয় মাসে আপনার নিজের প্রক্ষেপিত ব্যালান্স, দিনে দিনে, হাজার বার সিমুলেট করা। দ্বিতীয় রেখাটি সেই একই ছয় মাস, তবে এই কিস্তি বাদ দেওয়ার পর। দুইয়ের ব্যবধানই এই ঋণের প্রকৃত খরচ, আর বিন্দু-রেখাটি সেই স্তর যার নিচে আপনার কখনও নামা উচিত নয়।",
    afford_read_title: "নিজের রেখা কীভাবে পড়বেন",
    afford_read_1:
      "নিচের রেখাটি অনুসরণ করুন। এটি বিন্দু-রেখার উপরে থাকলে কিস্তিটি মানানসই।",
    afford_read_2:
      "নামগুলি লক্ষ করুন। প্রতিটি সেই মাস যখন টাকা আসার আগেই বেরিয়ে যায়।",
    afford_read_3: "ছায়া দেওয়া অংশটি খারাপ পরিস্থিতির — গড় নয়।",
    afford_verdict: "আপনার জন্য এর মানে কী",
    afford_clears: "নিচের সব পরীক্ষায় আপনার প্রক্ষেপিত ব্যালান্স নিরাপত্তা সঞ্চয়ের উপরে থাকে।",
    afford_fragile: "মাসে মাসে এটি চলবে। নিচের কোনো একটি ঘটলে চলবে না।",
    afford_breaches: "বর্তমান প্রক্ষেপণে আপনার ব্যালান্স নিরাপত্তা সঞ্চয়ের নিচে নেমে যায়।",
    afford_shocks: "পরপর কতবার আয় দেরি হলেও সামলাতে পারবেন",
    afford_shocks_note: "নিচের পরীক্ষাগুলি আপনার স্বাভাবিক মাসে একটি করে ধাক্কা যোগ করে। এটি তার চেয়ে কঠিন কিছু গোনে: পরপর কতবার আয় না এলেও আপনার নিরাপত্তা সঞ্চয় টিকে থাকবে।",
    afford_scenarios: "কিছু ভুল হলে",
    afford_lowest: "আপনার ব্যালান্স সর্বনিম্ন কত হবে",
    afford_stays_above: "আপনি উপরে থাকেন",
    afford_falls_below: "আপনি নিচে নেমে যান",
    afford_no_obligation_title: "এই মুহূর্তে কিছুই প্রস্তাব করা হচ্ছে না",
    afford_no_obligation_body:
      "যাচাই করার মতো কোনো কিস্তি নেই, তাই নিচের লেখচিত্রটি কেবল আপনার প্রক্ষেপিত ব্যালান্স দেখাচ্ছে। আপনি নিজের অবস্থা দেখতে পারেন বলেই এটি এখানে, আমরা কিছু চাইছি বলে নয়।",
    afford_structure_works: "যে কাঠামোটি কাজ করবে",

    agree: "আমি সম্মত",
    not_now: "এখন নয়",
    disagree: "আমি এই সিদ্ধান্তের সঙ্গে একমত নই",
    human_review: "একজন মানুষ এটি পর্যালোচনা করবেন",
    agree_recorded:
      "নথিভুক্ত হয়েছে। এরপর মূল তথ্য — নিশ্চিত করার আগে সেগুলি পড়ুন।",
    not_now_recorded:
      "ঠিক আছে। না বলা কখনও ঝুঁকির সংকেত হিসেবে রাখা হয় না, এবং আমরা শিগগিরই আবার জিজ্ঞেস করব না।",
    disagree_recorded:
      "আপনার আপত্তি নথিভুক্ত হয়েছে এবং একজন মানুষ এই সিদ্ধান্ত পর্যালোচনা করবেন। আপনাকে আর কিছু করতে হবে না।",
    disagree_help:
      "সিদ্ধান্ত ভুল মনে হলে এটি ব্যবহার করুন। এটি পূর্ণ যুক্তিসহ একজন মানুষের কাছে যায়, একই স্বয়ংক্রিয় যাচাইয়ে ফিরে যায় না।",
    back_to_overview: "সারসংক্ষেপে ফিরুন",

    key_facts: "মূল তথ্য",
    read_aloud: "পড়ে শোনান",
    kfs_numbers: "সংখ্যাগুলি",
    kfs_tenure: "দীর্ঘ মেয়াদের প্রকৃত খরচ",
    kfs_months: "মাস",
    kfs_every_month: "প্রতি মাসে",
    kfs_extra: "মোট অতিরিক্ত",
    kfs_warn:
      "ছোট মাসিক কিস্তি মানে ছোট ঋণ নয়। শেষ কলামটি বাড়তি মাসগুলির খরচ।",
    kfs_note:
      "মূল তথ্য বিবৃতির বিষয়বস্তু ও বিন্যাস যেকোনো বাস্তব ব্যবহারের আগে বর্তমান RBI ডিজিটাল লেন্ডিং নির্দেশিকার সঙ্গে মিলিয়ে নিতে হবে।",
    kfs_none_title: "এখন পড়ার মতো কোনো প্রস্তাব নেই",
    kfs_none_body:
      "নির্দিষ্ট অঙ্ক, সুদের হার ও কিস্তি থাকলে তবেই মূল তথ্য বিবৃতি তৈরি হয়। এই মুহূর্তে আপনাকে কিছুই দেওয়া হচ্ছে না, তাই এখানে সম্মত হওয়ার মতো কিছু নেই।",
    kfs_none_action: "আপনার কী দরকার বলুন",

    privacy: "আপনার তথ্য",
    data_used: "ব্যবহৃত",
    data_not_used: "স্পষ্টভাবে ব্যবহার করা হয়নি",
    revoke: "বন্ধ করুন",

    tap_to_speak: "বলতে চাপ দিন",
    listening: "শুনছি…",
    stop_listening: "থামান",
    voice_unsupported:
      "এই ব্রাউজার শুনতে পারে না। নিচে লিখুন বা একটি অনুরোধ বেছে নিন — বাকি যাত্রা একই থাকবে।",
    voice_demo_transcript: "ডেমো প্রতিলিপি",
    voice_use_request: "এই অনুরোধটি ব্যবহার করুন",
    voice_low_confidence: "কম-আস্থার লাইন পরীক্ষা করুন",

    safety_phrase: "আপনার নিরাপত্তা বাক্যাংশ",
    never_ask: "আমরা কখনও OTP, PIN বা CVV চাইব না",
    recovery_title: "আমরা আপনার সঙ্গে আছি",
    recovery_body: "এই মাসে আমরা আপনাকে নতুন কিছু বিক্রি করছি না।",
    talk_to_person: "একজন মানুষের সঙ্গে কথা বলুন",
    nothing_today: "আজ বলার মতো কিছু নেই",
    nothing_today_body:
      "কথা বলার দরকার হয় এমন কিছুই বদলায়নি। এটাই ব্যবস্থাটির ঠিকঠাক কাজ করার প্রমাণ।",

    arrears_title: "আপনার কিস্তি",
    arrears_up_to_date: "বকেয়া নেই",
    arrears_days_past_due: "দিন বকেয়া",
    arrears_missed: "কিস্তি বকেয়া",
  },
};

/** What the app can honestly claim about each language.
 *
 * Report §11.3 draws the line that matters: authored coverage is not machine
 * translation. Every string in this table, every reason-code template and the
 * whole Key Fact Statement are written out in all five languages, so a decision
 * really is rendered in the language the customer picked. What is *not* claimed
 * is live translation of anything outside those tables — the Bhashini and
 * AI4Bharat adapters are real interfaces with a stub provider that deliberately
 * does not fake translation, so free-form text from a live service is not
 * something this prototype has.
 *
 * The note therefore says what is true of the prototype rather than apologising
 * for a gap that no longer exists.
 */
export const LANGUAGE_COVERAGE_NOTE: Record<Lang, string> = {
  en: "",
  hi: "",
  mr: "या स्क्रीनवरील मजकूर मराठीत लिहिलेला आहे. थेट भाषांतर सेवा या नमुन्यात जोडलेली नाही.",
  ta: "இந்தத் திரையின் உரை தமிழில் எழுதப்பட்டுள்ளது. நேரடி மொழிபெயர்ப்புச் சேவை இந்த மாதிரியில் இணைக்கப்படவில்லை.",
  bn: "এই স্ক্রিনের লেখা বাংলায় লেখা হয়েছে। সরাসরি অনুবাদ পরিষেবা এই নমুনায় যুক্ত নেই।",
};

/** Languages the decision service authors its sentences in. All of them. */
export const GENERATED_TEXT_LANGUAGES: Lang[] = ["en", "hi", "mr", "ta", "bn"];

export function hasGeneratedText(lang: Lang): boolean {
  return GENERATED_TEXT_LANGUAGES.includes(lang);
}

export function t(lang: Lang, key: string): string {
  const value = STRINGS[lang]?.[key];
  if (value !== undefined) return value;
  // A missing key is a gap in this table, not something to paper over silently:
  // fall back to English so the screen still works, and say so in the console
  // so the gap is findable rather than invisible.
  if (import.meta.env.DEV && STRINGS.en[key] !== undefined) {
    console.warn(`[i18n] missing "${key}" for "${lang}" — falling back to English`);
  }
  return STRINGS.en[key] ?? key;
}
